### ISSUE TITLE
Error in Termux

### ISSUE THREAD

**Issue by xronin01** [juraj-hrivnak/Pakku#74]
![Screenshot_20241224-154411](https://github.com/user-attachments/assets/1d42598f-95b1-48f0-afc8-1eb497d9129b)

Pakku 0.24.1
Openjdk 17

**Comment by juraj-hrivnak** [comment]
@xronin01 Can you try it with [this build](https://github.com/juraj-hrivnak/Pakku/actions/runs/12610918591/artifacts/2385818754)?

**Comment by xronin01** [comment]
does not work on jdk 17 and 21

**Comment by xronin01** [comment]
termux does not have jdk 22
![Screenshot_20250104-131524](https://github.com/user-attachments/assets/d9f05353-71f8-40b8-a581-c42203267a67)

**Comment by juraj-hrivnak** [comment]
> does not work on jdk 17 and 21

It prints the same error?

**Comment by juraj-hrivnak** [comment]
Pakku should work on Java 8 and up

**Comment by xronin01** [comment]
Exception in thread "main" java.lang.UnsupportedOperationException: Cannot find terminal interface that supports raw mode.                                                                                                  You need at least one of the `:mordant-jvm-*` modules on your classpath.
The `:mordant` module includes all of them as transitive dependencies.
If you're using `:mordant-core` instead, you need to add one or more manually.                                              If you're using only `:mordant-jvm-ffm`, make sure you're running with JVM 22+, and are passing
`--enable-native-access=ALL-UNNAMED` as a JVM argument.

        at com.github.ajalt.mordant.internal.DumbTerminalInterface.enterRawMode(MppInternal.jvm.kt:173)
        at com.github.ajalt.mordant.input.RawModeKt.enterRawMode(RawMode.kt:19)
        at com.github.ajalt.mordant.input.ReceiveEventsKt.receiveEvents(ReceiveEvents.kt:16)
        at com.github.ajalt.mordant.input.InteractiveSelectListKt.interactiveSelectListString(InteractiveSelectList.kt:110)
        at teksturepako.pakku.cli.cmd.Init$run$1.invokeSuspend(Init.kt:75)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:47)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at teksturepako.pakku.cli.cmd.Init.run(Init.kt:19)
        at com.github.ajalt.clikt.core.CoreCliktCommandKt.parse(CoreCliktCommand.kt:107)
        at com.github.ajalt.clikt.core.CoreCliktCommandKt.main(CoreCliktCommand.kt:78)
        at com.github.ajalt.clikt.core.CoreCliktCommandKt.main(CoreCliktCommand.kt:90)
        at teksturepako.pakku.MainKt.main(Main.kt:33)

**Comment by juraj-hrivnak** [comment]
Should be fixed in https://github.com/juraj-hrivnak/Pakku/actions/runs/12612092161
It will use the simple prompt on Termux

**Comment by xronin01** [comment]
https://github.com/user-attachments/assets/31a1d395-2cd1-44e0-9e85-32cca5ca2497

**Comment by juraj-hrivnak** [comment]
I see. Okay this will be harder to fix.

**Comment by juraj-hrivnak** [comment]
https://github.com/ajalt/mordant/issues/247

**Comment by juraj-hrivnak** [comment]
In v1.0.0, you can use the [options](https://juraj-hrivnak.github.io/Pakku/pakku-init.html#options) to init the modpack.
